all:
  children:
    managed_vms:
      hosts:
        r:
          ansible_host: 192.168.122.71
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
