all:
  children:
    managed_vms:
      hosts:
        load-test-1:
          ansible_host: 192.168.122.3
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-2:
          ansible_host: 192.168.122.249
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: []
        load-test-3:
          ansible_host: 192.168.122.33
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-4:
          ansible_host: 192.168.122.119
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-5:
          ansible_host: 192.168.122.39
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-6:
          ansible_host: 192.168.122.18
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-7:
          ansible_host: 192.168.122.248
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-8:
          ansible_host: 192.168.122.47
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-9:
          ansible_host: 192.168.122.244
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-10:
          ansible_host: 192.168.122.245
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [SSH, HTTP_SERVER]
        load-test-11:
          ansible_host: 192.168.122.69
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-12:
          ansible_host: 192.168.122.208
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-13:
          ansible_host: 192.168.122.113
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [SSH, HTTP_SERVER]
        load-test-14:
          ansible_host: 192.168.122.210
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-15:
          ansible_host: 192.168.122.224
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-16:
          ansible_host: 192.168.122.140
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-17:
          ansible_host: 192.168.122.53
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [SSH, HTTP_SERVER]
        load-test-18:
          ansible_host: 192.168.122.152
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-19:
          ansible_host: 192.168.122.206
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [HTTP_SERVER, SSH]
        load-test-20:
          ansible_host: 192.168.122.147
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [SSH, HTTP_SERVER]
        kostya-vmm:
          ansible_host: 192.168.122.247
          ansible_user: alpine
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /tmp/diploma_ansible_id_rsa
          ansible_ssh_common_args: '-o ProxyJump=root@89.104.68.81 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          environment_packages: [SSH, HTTP_SERVER, DOCKER]
