spring.application.name=backend
server.port=8080

spring.datasource.url=${BACKEND_DB_URL:jdbc:postgresql://localhost:5433/diploma}
spring.datasource.username=${BACKEND_DB_USER:postgres}
spring.datasource.password=${BACKEND_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.jakarta.persistence.jdbc.url=${spring.datasource.url}
spring.jpa.properties.jakarta.persistence.jdbc.user=${spring.datasource.username}
spring.jpa.properties.jakarta.persistence.jdbc.password=${spring.datasource.password}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
